function PrimaryButton() {
  return(
    <div
      className="
        flex
        flex-row
        justify-around
        items-center
        rounded-full 
        bg-primary
        hover:bg-primary-light
        w-[90px]
        h-[44px]
        md:w-[150px]
        md:h-[48px]
        font-[700]
        cursor-pointer
        text-[12px]
      "
    >
      <div 
        className="
          flex
          justify-center
          items-center
          plus-icon
          rounded-full
          w-[32px]
          h-[32px]
          bg-white
          ml-1
          md:ml-0
        "
      >
        <img 
          src="/assets/icon-plus.svg" 
          alt="Add button" 
          className="
            md:pl-0.5
          "
        />
      </div>
      <div 
        className="
          flex
          text 
          pr-2.5 
          pt-1
          text-white
          md:text-[13px]
        "
      >
        <span>
          New
        </span>
        <span
          className="
            hidden
            md:block
            ml-1
          "
        >Invoice</span>
      </div>
    </div>
  )
}

export default PrimaryButton